/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryType' : IDL.Text,
  'notes' : IDL.Text,
  'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'phoneNumber' : IDL.Text,
});
export const Reservation = IDL.Record({
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'specialRequests' : IDL.Text,
  'partySize' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const ReservationId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getReservation' : IDL.Func([ReservationId], [Reservation], ['query']),
  'submitOrder' : IDL.Func([Order], [OrderId], []),
  'submitReservation' : IDL.Func([Reservation], [ReservationId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryType' : IDL.Text,
    'notes' : IDL.Text,
    'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'phoneNumber' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'specialRequests' : IDL.Text,
    'partySize' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const ReservationId = IDL.Nat;
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getReservation' : IDL.Func([ReservationId], [Reservation], ['query']),
    'submitOrder' : IDL.Func([Order], [OrderId], []),
    'submitReservation' : IDL.Func([Reservation], [ReservationId], []),
  });
};

export const init = ({ IDL }) => { return []; };